### ISSUE TITLE
isAhStageEnv() doesn't work in ACE stage environment

### ISSUE THREAD

**Issue by gauravgoyal** [acquia/drupal-environment-detector#11]
[isAhStageEnv()](https://github.com/acquia/drupal-environment-detector/blob/master/src/AcquiaDrupalEnvironmentDetector.php#L74) returns `TRUE` if environment name has "test" or "stg", however on ACE stage, environment name is `stage`.

**Comment by danepowell** [comment]
I've been told that _stg_ is the old convention and _test_ is the new convention for ACE staging environments, but _stage_ is not part of any convention. It seems like your application was created as part of a non-standard process, and the best solution would be to get that environment renamed.

We should also probably document this in the code somewhere. I wasn't aware of these conventions or the possibility for manual exceptions.

**Comment by msherron** [comment]
@danepowell - I did some homework on this, the convention you mention is true, but it isn't really enforced - our ops process lets them create environments and essentially name them whatever they want. I can share with you privately a list of application environments that have the name `stage` - it's not huge, but it's not zero either. Also, customers can ask for new environments that have a totally custom name which this plugin won't detect - e.g., 'QA', 'UAT', etc. I think this is a good use case for us to detect those custom environments on our side (in ACMS), but just wanted to relay that info.

**Comment by danepowell** [comment]
Thanks for following up. I guess if the number of customers with `stage` is >1, we can merge it. I just don't want to set a precedent for supporting every conceivable name, spelling, and misspelling of an environment.
