### ISSUE TITLE
Count LANDO as Local

### ISSUE THREAD

**Issue by nikunjkotecha** [acquia/drupal-environment-detector#22]
With `acquia` recipe of Lando we get LANDO for AH_SITE_ENVIRONMENT environment variable.

https://docs.lando.dev/config/acquia.html

Since this returns true lot of additional code is executed in local which is actually not required.

Steps to reproduce - Setup new project with Acquia CMS default steps using Lando and use `acquia` recipe for it.

**Comment by danepowell** [comment]
Clarification: Lando _is_ already considered local. It's _also_ considered an AH environment.

**Comment by nikunjkotecha** [comment]
@danepowell It seems we need to update the function isAhEnv (assuming AH here means Acquia Hosting)

as checked in https://github.com/acquia/drupal-environment-detector/blob/master/src/AcquiaDrupalEnvironmentDetector.php#L13 it returns true even for LANDO and that is causing problems in conditions based on this function.

**Comment by danepowell** [comment]
What problems? It _is_ an Acquia hosting environment, albeit one that you run locally. But the file structure and available resources should all be the same.

**Comment by nikunjkotecha** [comment]
See https://github.com/acquia/acquia_cms/blob/develop/patches/d9-acms-settings.patch

In Acquia CMS the condition is to execute some code on AH environment and that condition returns true even in LANNDO since the variable is set and the only condition inside isAhEnv is that if the variable is set or not.

Question (sorry for stepping back):
* Does AH here mean Acquia Hosting?
* If yes, shouldn't we have better check in isAhEnv?
* If no, do we have a release note or something to go to Acquia CMS team saying that condition needs to be updated / fixed?

**Comment by danepowell** [comment]
Again, I don't see what problem that conditional is causing, can you provide an example? It essentially just includes database settings, which is desirable (Acquia Lando environments provide DB settings just like Acquia Cloud). It shouldn't cause problems.

**Comment by nikunjkotecha** [comment]
We don't have /var/www/site-php/ in Lando
