### ISSUE TITLE
1.1.0 release?

### ISSUE THREAD

**Issue by wimleers** [acquia/drupal-environment-detector#4]
https://github.com/acquia/drupal-environment-detector/commit/bd0907d443ba5d2109262dcdfb5679f36ed5aa83 added important new methods. But they're not yet available in a stable release.

The https://github.com/acquia/drupal-environment-detector/releases/tag/v1.0.0 release tagged the commit just before the aforementioned one.

Any chance you could tag a new release? 🙏 😊

**Comment by danepowell** [comment]
https://github.com/acquia/drupal-environment-detector/releases/tag/v1.1.0

**Comment by wimleers** [comment]
🥳  Thank you!
