### ISSUE TITLE
DX-5160: ahFilesRoot incorrectly sets files on Cloud IDE

### ISSUE THREAD

**Issue by fiasco** [acquia/drupal-environment-detector#43]
Cloud IDE does not have /mnt/files but is assumed so in https://github.com/acquia/drupal-environment-detector/blob/master/src/FilePaths.php#L60

When using BLT config splits, this causes failures in drupal install attempts.

**Comment by anavarre** [comment]
Discussed this with Josh and it works on mine so it's not an environment detector issue.

**Comment by danepowell** [comment]
Sounds like not an issue
