### ISSUE TITLE
DX-5169: acquia/blt and acquia/drupal-environment-detector returns empty strings

### ISSUE THREAD

**Issue by martinmoralesh** [acquia/drupal-environment-detector#50]
Currently the acquia/blt and acquia/drupal-environment-detector dependencies are set to specific releases (13.5.1 and 1.4.1) because updating cause the base_path in site to be returned as an empty string.

**Comment by fullstackmike** [comment]
Here is a better summary of this issue for anyone trying to rectify ... 
https://github.com/acquia/blt/discussions/4594

**Comment by danepowell** [comment]
I believe this was solved by #55
